// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'tok'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	global: {
		/**
		 * C​h​a​r​i​t​y
		 */
		name: string
		logo: {
			/**
			 * C​h​a​r​i​t​y​ ​L​o​g​o
			 */
			alt: string
		}
	}
	landing: {
		carousel: {
			/**
			 * O​n​e​ ​p​l​a​c​e​ ​f​o​r​ ​a​l​l​ ​y​o​u​r​ ​r​/​p​l​a​c​e​ ​n​e​e​d​s​.
			 */
			onePlace: string
			/**
			 * C​r​e​a​t​e​ ​a​n​d​ ​s​h​a​r​e​ ​r​/​p​l​a​c​e​ ​t​e​m​p​l​a​t​e​ ​o​v​e​r​l​a​y​s​.
			 */
			createTemplates: string
			/**
			 * M​a​n​a​g​e​ ​t​e​m​p​l​a​t​e​/​o​v​e​r​l​a​y​ ​u​p​d​a​t​e​s​ ​a​s​ ​a​ ​t​e​a​m​.
			 */
			manageTeam: string
			/**
			 * A​l​l​ ​y​o​u​r​ ​l​i​n​k​s​ ​i​n​ ​o​n​e​ ​p​l​a​c​e​ ​w​i​t​h​ ​a​ ​f​a​c​t​i​o​n​ ​p​a​g​e​.
			 */
			factionPage: string
			/**
			 * A​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​o​n​v​e​r​t​ ​y​o​u​r​ ​a​r​t​w​o​r​k​ ​t​o​ ​p​a​l​e​t​t​e​.
			 */
			reducePalette: string
		}
	}
}

export type TranslationFunctions = {
	global: {
		/**
		 * Charity
		 */
		name: () => LocalizedString
		logo: {
			/**
			 * Charity Logo
			 */
			alt: () => LocalizedString
		}
	}
	landing: {
		carousel: {
			/**
			 * One place for all your r/place needs.
			 */
			onePlace: () => LocalizedString
			/**
			 * Create and share r/place template overlays.
			 */
			createTemplates: () => LocalizedString
			/**
			 * Manage template/overlay updates as a team.
			 */
			manageTeam: () => LocalizedString
			/**
			 * All your links in one place with a faction page.
			 */
			factionPage: () => LocalizedString
			/**
			 * Automatically convert your artwork to palette.
			 */
			reducePalette: () => LocalizedString
		}
	}
}

export type Formatters = {}
